on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.36
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        binary_name: nxm-${{ matrix.goos }}-${{ matrix.goarch }}
        asset_name: nxm-${{ matrix.goos }}-${{ matrix.goarch }}
        compress_assets: false