on:
  release:
    types: [created]

env:
  BINARY_NAME: nxm-${{ release.goos }}-${{ release.goarch }}

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.36
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        asset_name: env.BINARY_NAME
        compress_assets: false