---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "tagged release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: "Build & test"
        run: |
          go get .
          go build -o nxm

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: nxm